name: socialapps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.36

environment:
  sdk: '>=2.19.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  time_picker_spinner_pop_up: ^1.0.3
  http: ^0.13.6
  fluttertoast: ^8.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.1.0
  #  razorpay_flutter: ^1.3.5
  flutter_rating_bar: ^4.0.1
  lottie: ^2.3.2
  webview_flutter: ^3.0.4
  path_provider: ^2.0.15
  geolocator: ^9.0.2
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.0
  google_maps_flutter: ^2.2.6
  location: ^4.4.0
  permission_handler: ^10.2.0
  wheel_chooser: ^1.1.2
  file_picker: ^5.2.5
  dotted_border: ^2.0.0+3
  get: ^4.6.5
  dropdown_button2: ^2.0.0
  pin_code_fields: ^7.4.0
  dots_indicator: ^2.1.0
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  flutter_typeahead: ^4.6.1
  place_picker: ^0.10.0
  mask_text_input_formatter: ^2.4.0
  cached_network_image: ^3.2.3
  image_picker: ^1.0.0
  flutter_switch: ^0.3.2
  #  notification
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  flutter_local_notifications: ^15.1.0+1
  flutter_reaction_button: ^2.0.1+2
  month_picker_dialog: ^2.0.2
  image_cropper: ^4.0.0
  flutter_simple_multiselect: ^2.0.0
  custom_searchable_dropdown: ^2.1.1
  device_info_plus: ^8.2.2
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.10
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  video_player: ^2.7.2
  flick_video_player: ^0.5.0
  video_thumbnail: ^0.5.3
  camera: ^0.10.5+5
  flutter_html: any
  flutter_config: ^2.0.2
  simple_rich_text: ^2.0.49

#  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/

  fonts:
    - family: Roboto900
      fonts:
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 900
          
    - family: Roboto700
      fonts:
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 900

    - family: Montserrat600
      fonts:
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 900

    - family: Montserrat500
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900

    - family: Roboto500
      fonts:
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 900

    - family: Roboto400
      fonts:
        - asset: assets/fonts/DroidSans.ttf
          weight: 900

    - family: Roboto300
      fonts:
        - asset: assets/fonts/DroidSans.ttf
          weight: 900

    - family: Roboto100
      fonts:
        - asset: assets/fonts/DroidSans.ttf
          weight: 900








